name: testing first pipeline
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: hihi
        run: |
          ls
          echo "check from system"
          echo "hello world" >> gappu.txt
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: file
          path: gappu.txt

